### PR TITLE
Implement hook_merge to migrate civigeometry_geometry_entity records

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by andrew-cormick-dockery** [comment]
I'm trying to work out how this relates to contact merges.  Looking at the entity_table column in this table reveals this:

image

Note that civicrm_contact isn't there.  Only civicrm_address apparently demands different treatment, even though there are election related entities there.  I'm really interested in understanding your thinking here.

**Comment by seamuslee001** [comment]
@andrew-cormick-dockery as part of other work we will be wanting to migrate the manual placements etc from agc_contact_poly to civigeometry_geometry_entity and as such will need to be considering how to handle them in a merge.

**Comment by andrew-cormick-dockery** [comment]
OK I get it now.  Let's ensure it's all tested properly before merging.

**Comment by johntwyman** [comment]
@seamuslee001 will this need a revisit given the addition of the expiry date column? Looking at the diff I shouldn't think so.

**Comment by seamuslee001** [comment]
Unlikely no

**Pull request merged**
