### PR TITLE
Add index to geometry-entity table

### PR DESCRIPTION
**Pull request by johntwyman**
This PR adds a new index to the civigeometry_geometry_entity table to improve system performance. The existing compound index, while optimised for many of the queries made against the table, isn't optimal for queries of the form `WHERE entity_table = X and entity_id = Y`.

The index has been tested in dev and production already and has been removed ahead of the deployment of this PR/update.

### CODE REVIEW

**Comment by anthonyblond** [comment]
Great idea. 

For reference the current index is on (entity_table, geometry_id, entity_id), so now we'll have that and (entity_table, entity_id)

**Review by anthonyblond — APPROVED** [review]

**Comment by seamuslee001** [comment]
@johntwyman don't you need to update the table xml as well?

**Review by andrew-cormick-dockery — APPROVED** [review]

**Comment by johntwyman** [comment]
> @johntwyman don't you need to update the table xml as well?

I do. I'll fix that and update accordingly.

**Comment by johntwyman** [comment]
@seamuslee001 I've updated the schema XML and run `civix generate:entity-boilerplate`.  I think we're good now, right?

**Pull request merged**
