### PR TITLE
Add in APIv4 Entities and Actions for CiviGeometry Entities and Methods

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Comment by andrew-cormick-dockery** [comment]
It appears that you're testing the v4 api against the v3 tests, which I don't doubt is legitimate, however it does make me wonder about the test structure for the api.  From a readability point of view, files in a directory named `/tests/phpunit/api/v3/` wouldn't intuitively cover both versions 3 and 4.

**Comment by seamuslee001** [comment]
@andrew-cormick-dockery This is standard as per core, see also https://github.com/civicrm/civicrm-core/blob/master/tests/phpunit/api/v3/RelationshipTest.php#L97, there is https://github.com/civicrm/civicrm-core/blob/master/Civi/Test/Api3TestTrait.php#L290 https://github.com/civicrm/civicrm-core/blob/master/Civi/Test/Api3TestTrait.php#L306 which basically converts the APIv3 test into APIv4 format

**Comment by colemanw** [comment]
This code contains a lot of boilerplate copied from the Generic actions.
My hope in writing those generic classes was that they could be extended instead of copied.
Have you looked at how https://lab.civicrm.org/extensions/api4example makes use of the `BasicAction` classes? I've found them to be very flexible, they've made implementing apis for "nonstandard" entities quite simple. Afform and CiviTutorial both use them and it keeps the boilerplate code out nicely.

**Comment by seamuslee001** [comment]
@colemanw when I looked at the DAOAction classes e.g. DAOCreate etc it didn't seem obvious how I would intervene before the writing happened and also after writing, if you notice in the create and update I handle for the case where we are uploading Feature Collections i.e. one string of GeoJSON which contains n actual geometries within it. Then we return by default GeoJSON string rathe than Well Known Binary (WKB) format which is what is stored in the MySQL database. Similar in the Get Action we support outputting of Geometry in multiple formats (KML, GeoJSON, Well Knwon Text (WKT))  and it wasn't clear how I should be modifying the output of the Get request.  so in these cases I figured the only way was to override the _run function

Also in the get we handle for a collection_id which is a CiviGeometryColletion id to be passed in as a limiting parameter but that required adding in some extra joins because we didn't want to actually expose the Bridge Entity in the API layer.

**Review by johntwyman — APPROVED** [review]

**Review by unfinishedteleporter — APPROVED** [review]
Approving on assumption the typo will be fixed.
Happy to approved since its an extra feature that isn't made use of anywhere...yet, and passes tests.

**Comment by seamuslee001** [comment]
> Approving on assumption the typo will be fixed.
> Happy to approved since its an extra feature that isn't made use of anywhere...yet, and passes tests.

@unfinishedteleporter @johntwyman fixed the typo now

**Comment by colemanw** [comment]
@seamuslee001 typically pre/post processing goes into the `BAO::create` function or (and I think this is a bit cleaner) in pre/post hooks.
Putting it in the API layer means the api code is more complex and hard to reuse between api v3 and v4 (and someday v5).

**Pull request merged**
